version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: docker_db
    environment:
      POSTGRES_DB: chat_api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - chat_network
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    image: sophakz/studnet-api-springboot
    container_name: springboot_chat
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chat_api
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - chat_network
networks:
  chat_network:
    driver: bridge

