spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tb_student
    username: postgres
    password: phak1502
  jpa:
    database-platform:
    hibernate:
      ddl-auto: update
    show-sql: true